mesh:
  Re: 1.0
  H: 1.0
  N: 10

materials:
  E: 1.44e10
  nu: 0.2
  alpha: 0.78
  perm: 1.9e-13
  visc: 1.0e-3
  M: 1.35e10

boundary_conditions:
  bottom: # z=0
    sig_zz: -1.0e5
    Pressure: 0.0

  top:
    U_z: 0.0
  
  right:
    U_r: 0.0
  
  left:
    U_r: 0.0

numerical:
  end_time: 1
  dt0   : 0.005
  dtk   : 1.0001
  dtmax : 0.005
  num_steps: 100000
  theta_cn: 1.0

output:
  vtk_file: "outputs/results.bp"
  fem_timeseries_file: "outputs/fem_timeseries.nc"
  analytical_timeseries_file: "outputs/analytical_timeseries.nc"
  output_dir: "outputs"
